### ISSUE TITLE
Requiring clearance rspec helper breaks rspec.

### ISSUE THREAD

**Issue by txdavidtx** [thoughtbot/clearance#531]
When I add the require statement ```require "clearance/rspec"``` to use ```Clearance::BackDoor``` it breaks rspec and gives the following error:
```
/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant Module::ActiveSupport (NameError)
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/actionview-4.2.0/lib/action_view/template/resolver.rb:2:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/actionview-4.2.0/lib/action_view/template/resolver.rb:2:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/actionview-4.2.0/lib/action_view/testing/resolvers.rb:1:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/actionview-4.2.0/lib/action_view/testing/resolvers.rb:1:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-rails-3.1.0/lib/rspec/rails/view_rendering.rb:1:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-rails-3.1.0/lib/rspec/rails/view_rendering.rb:1:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-rails-3.1.0/lib/rspec/rails.rb:4:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-rails-3.1.0/lib/rspec/rails.rb:4:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/clearance-1.8.0/lib/clearance/rspec.rb:1:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/clearance-1.8.0/lib/clearance/rspec.rb:1:in `<top (required)>'
	from /Users/davidhunt/workspace/daisy/spec/spec_helper.rb:1:in `require'
	from /Users/davidhunt/workspace/daisy/spec/spec_helper.rb:1:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/bin/rspec:23:in `load'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/bin/rspec:23:in `<main>'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/davidhunt/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```
I read about an issue with rspec that has since been resolved [here](https://github.com/rails/rails/issues/17936) which I thought may have something to do with it, but it doesn't seem to be the issue necessarily.

Any ideas for a work around or solution?

**Comment by pedrosmmoreira** [comment]
@txdavidtx, the error you are seeing is due to requiring `clearance/rspec` in your `spec_helper` file. From the backtrace, you see the actual error is due to ActiveSupport not being initialized. Since you are using RSpec 3, the require should be place in your `spec/rails_helper`, which loads the Rails env.

Also, in order to use the `BackDoor` middleware, you just need to add it to your `config/environments/test.rb`, [as indicated in the README](https://github.com/thoughtbot/clearance#fast-feature-specs). Requiring `clearance/rspec` is only necessary for use of convenience methods in controller tests.

I've submitted a PR to update the instructions https://github.com/thoughtbot/clearance/pull/534

**Comment by derekprior** [comment]
Thanks, @pedrosmmoreira
