### ISSUE TITLE
`./bin/setup` dies with stack level too deep

### ISSUE THREAD

**Issue by IzumiSy** [thoughtbot/clearance#760]
I tried to run `./bin/setup` to prepare for my pull request, but it dies with Ruby 2.4.0. Is there any chance to catch up with this?
```
vagrant@vagrant:~/devs/clearance
$ rbenv global 2.4.0
vagrant@vagrant:~/devs/clearance
$ ./bin/setup
Warning: the running version of Bundler (1.15.3) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
The Gemfile's dependencies are satisfied
Warning: Your gemfiles directive in .travis.yml is incorrect. Run `appraisal generate --travis` to get the correct configuration.
>> bundle check --gemfile='/home/vagrant/devs/clearance/gemfiles/rails40.gemfile' || bundle install --gemfile='/home/vagrant/devs/clearance/gemfiles/rails40.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/vagrant/devs/clearance/gemfiles/rails41.gemfile' || bundle install --gemfile='/home/vagrant/devs/clearance/gemfiles/rails41.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/vagrant/devs/clearance/gemfiles/rails42.gemfile' || bundle install --gemfile='/home/vagrant/devs/clearance/gemfiles/rails42.gemfile'
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/home/vagrant/devs/clearance/gemfiles/rails50.gemfile' || bundle install --gemfile='/home/vagrant/devs/clearance/gemfiles/rails50.gemfile'
The Gemfile's dependencies are satisfied
/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/home/vagrant/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
rake aborted!
SystemStackError: stack level too deep
/home/vagrant/devs/clearance/spec/dummy/application.rb:50:in `initialize!'
/home/vagrant/devs/clearance/spec/dummy/application.rb:45:in `require_environment!'
/home/vagrant/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/home/vagrant/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
Tasks: TOP => dummy:db:reset => dummy:environment
(See full trace by running task with --trace)
```

**Comment by joshmfrankel** [comment]
Same issue here @IzumiSy. Were you able to solve it? 

```
/home/josh/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
/home/josh/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/home/josh/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
rake aborted!
SystemStackError: stack level too deep
/home/josh/Development/projects/forks/clearance/spec/dummy/application.rb:50:in `initialize!'
/home/josh/Development/projects/forks/clearance/spec/dummy/application.rb:45:in `require_environment!'
/home/josh/.asdf/installs/ruby/2.4.2/bin/bundle:23:in `load'
/home/josh/.asdf/installs/ruby/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => dummy:db:reset => dummy:environment
```

**Comment by IzumiSy** [comment]
@joshmfrankel I finally managed to solve that with Ruby 2.4.1. That might be the latest Ruby version which works with clearance,.

**Comment by joshmfrankel** [comment]
> @joshmfrankel I finally managed to solve that with Ruby 2.4.1. That might be the latest Ruby version which works with clearance,.

Thanks! I'll give that a shot

**Comment by mjankowski** [comment]
I'm going to close this on the assumption that no one needs to run 2.4 to open PRs at this point, but if you do need to and still have this issue, by all means re-open.
