### ISSUE TITLE
clearance writes two different cookies, clobbering settings like `httponly`

### ISSUE THREAD

**Issue by dholdren** [thoughtbot/clearance#766]
### Problem: httponly setting has no affect
I set `Clearance.configuration.httponly = true` but I noticed that executing `document.cookie` in Chrome's inspector still contained `remember_token`, then I realized that clearance was setting this cookie twice, once with `httponly`, and once without it.

Here's a spec that demonstrates the problem:
https://github.com/CasperSleep/clearance/commit/6f930bc235ed70f7b26750157ef66aaf7d89b30e

```
Failures:

  1) cookie options when httponly config value true sign in should have one remember_token cookie
     Failure/Error: expect(@remember_token_cookies.length).to eq(1), "expected one 'remember_token' cookie:\n#{@remember_token_cookies}"

       expected one 'remember_token' cookie:
       ["remember_token=1b3f09cead4c3ba39bed8ac0831837b0ea52a7b1; path=/; expires=Sat, 05 Jan 2019 18:04:16 -0000; HttpOnly", "remember_token=1b3f09cead4c3ba39bed8ac0831837b0ea52a7b1; path=/"]
     # /Users/dholdren/Dropbox (Personal)/third_party/clearance/spec/requests/cookie_options_spec.rb:41:in `block (4 levels) in <top (required)>'

  2) cookie options when httponly config value true sign in should have the httponly flag set
     Failure/Error: expect(@remember_token_cookies.last).to match(/httponly/i)

       expected "remember_token=fe6e5ed40284f7a724387fd25a2b2524918a9279; path=/" to match /httponly/i
       Diff:
       @@ -1,2 +1,2 @@
       -/httponly/i
       +"remember_token=fe6e5ed40284f7a724387fd25a2b2524918a9279; path=/"

     # /Users/dholdren/Dropbox (Personal)/third_party/clearance/spec/requests/cookie_options_spec.rb:45:in `block (4 levels) in <top (required)>'

  3) cookie options when httponly config value false sign in should have one remember_token cookie
     Failure/Error: expect(@remember_token_cookies.length).to eq(1), "expected one 'remember_token' cookie:\n#{@remember_token_cookies}"

       expected one 'remember_token' cookie:
       ["remember_token=5323f9bdb472031440d20a7283672d6590f856e8; path=/; expires=Sat, 05 Jan 2019 18:04:16 -0000", "remember_token=5323f9bdb472031440d20a7283672d6590f856e8; path=/"]
     # /Users/dholdren/Dropbox (Personal)/third_party/clearance/spec/requests/cookie_options_spec.rb:20:in `block (4 levels) in <top (required)>'

Finished in 0.39193 seconds (files took 1.16 seconds to load)
4 examples, 3 failures

Failed examples:

rspec /Users/dholdren/Dropbox (Personal)/third_party/clearance/spec/requests/cookie_options_spec.rb:40 # cookie options when httponly config value true sign in should have one remember_token cookie
rspec /Users/dholdren/Dropbox (Personal)/third_party/clearance/spec/requests/cookie_options_spec.rb:44 # cookie options when httponly config value true sign in should have the httponly flag set
rspec /Users/dholdren/Dropbox (Personal)/third_party/clearance/spec/requests/cookie_options_spec.rb:19 # cookie options when httponly config value false sign in should have one remember_token cookie
```
 
### Possible solution
https://github.com/thoughtbot/clearance/pull/617 looks correct, but it was not approved and was abandonded

**Comment by dholdren** [comment]
I now have a fix here: https://github.com/thoughtbot/clearance/pull/767
